### ISSUE TITLE
Missing conformer config files?

### ISSUE THREAD

**Issue by ulucsahin** [sooftware/kospeech#109]
## Title
- Training Config File for Conformer Models

## Description
I am trying to train conformer-small model. On the readme it says the command line argument "conformer_large_train" should be passed for training conformer model. But I am unable to locate config file conformer_large_train. Is it currently not available or am I missing? Thanks.

## Linked Issues
  
- resolved #

**Comment by sooftware** [comment]
In Hydra, configuration can manage using class. Check https://github.com/sooftware/KoSpeech/blob/latest/kospeech/trainer/__init__.py

**Comment by ulucsahin** [comment]
You are right, I missed that part. Thanks for the answer, I am closing the issue.
