### ISSUE TITLE
ValueError: Size of available data is not a multiple of the data-type size.

### ISSUE THREAD

**Issue by JoungheeKim** [sooftware/kospeech#110]
파일을 불러올 때 다음과 같은 에러가 발생하는 파일들이 있습니다.
ValueError: Size of available data is not a multiple of the data-type size.

에러가 발생하는 지점은
https://github.com/sooftware/KoSpeech/blob/4e8220b91cf47bebe2c93bcc43afedc0c16553a7/kospeech/data/audio/core.py#L31

Aihub에서 제공해 주는 kspon 데이터는 총 6가지로 나뉘어 있습니다.
1. KsponSpeech-Data part1
2. KsponSpeech-Data part2
3. KsponSpeech-Data part3
4. KsponSpeech-Data part4
5. KsponSpeech-Data part5
6. KsponSpeech_eval

6번째 파일인 "KsponSpeech_eval" 에서 파일을 불러올 때 위와 같은 에러가 발생합니다.
구체적인 파일 이름의 예는 아래와 같습니다.
eval_clean/KsponSpeech_E02262.pcm
eval_other/KsponSpeech_E05054.pcm

혹시 에러가 발생하는 이유에 대해서 알 수 있을까요??

**Comment by sooftware** [comment]
에러 로그를 같이 첨부해주세요.
