### ISSUE TITLE
main.py 이용하여 trian시 valueError 문의드립니다.

### ISSUE THREAD

**Issue by miziworld** [sooftware/kospeech#112]
python3 ./bin/main.py model=transformer train=transformer_train train.dataset_path=/home/user1/Downloads/korean_dataset/KsponSpeech_01/
이렇게 command 입력하였을때 다음과 같은 에러가 발생합니다.
제 생각에는 data_loader.py에서 경로변수들을 제대로 못받아오는것같은데 어떻게 해결해야할까요?
![image](https://user-images.githubusercontent.com/17849068/107917505-5f116b80-6fab-11eb-8c9e-6dc69b30b001.png)

**Comment by sooftware** [comment]
transcripts.txt 및 오디오 경로 제대로 설정되어 있나요?

**Comment by sooftware** [comment]
아마 transcrtips.txt의 경로가 잘못 설정되어 있을 것 같아요.

**Comment by miziworld** [comment]
Dataset path에서 Kspon 데이터셋 경로에 transcripts.txt를 같이 넣어주면 될까요? 한번 시도해보겠습니다

**Comment by sooftware** [comment]
data 폴더안에 transcripts.txt를 넣어주세요.

**Comment by miziworld** [comment]
data폴더안에 transcripts.txt도 넣어주고 경로도 제대로 설정해주었는데 똑같은 에러가 발생합니다....

**Comment by miziworld** [comment]
지금 Kspon dataset 경로는 /home/Downloads/KoSpeech-latest/kospeech/data/korean_dataset/ 에 있고 korean_dataset폴더 안에는 KsponSpeech_01과 transcripts.txt가 있습니다. KsponSpeech_01 안에는 KsponSpeech_0001~KsponSpeech_0124파일들이 존재합니다. transcripts.txt파일을 이중에 어디로 넣어주어야 할까요?

그리고 main.py를 실행시킬 때 argument로 넣어주는 train.train_dataset_path는 KsponSpeech_01이 있는 경로로 주어야 하나요 아니면 어떤 경로로 넣어주어야 할까요? 

transcripts.txt 경로는 KpoSpeech-latest/configs/train/transformer_train.yaml에서 설정해주었습니다.
 
그리고 data_loader.py를 보면 audio_path를 받아오는것 같은데 따로 설정해주지 않아도 되는건가요? 이때문에 문제가 발생하는것 같기도 합니다. 잘 몰라서 상세히 여쭤보는점 죄송합니다.
