### ISSUE TITLE
How do you train Librispeech dataset?

### ISSUE THREAD

**Issue by spygaurad** [sooftware/kospeech#113]
## Title
Training in Librispeech Data.
- 

## Description
The pipeline gives config errors when training with Librispeech data.

**Comment by sooftware** [comment]
Sorry to late respond. This project focused on Korean ASR. Previously, I had also created code to support LibriSpeech, but it failed to update to suit LibriSpeech due to the recent high number of code updates.Sorry for inconvenience.
