### ISSUE TITLE
1 epoch 이후로 학습이 진행되지 않거나 epoch_time_step 을 지나도 계속 학습되는 문제

### ISSUE THREAD

**Issue by miziworld** [sooftware/kospeech#115]
안녕하세요, 저번에 질문드렸던 경로문제는 해결이 되었는데
이번에는 에포치가1번밖에 실행이 되지 않고 supervised_trainer.py 에서 epoch, epoch_time_step, batch_size 등을 수정해주었습니다.  코드를 보니 num_workers는 발생되는 스레드 개수이고 input.shape[0]==0일때 스레드개수를 하나씩 감소시켜 num_workers=0이 되었을때 break되게 코드가 작성된것 같습니다.
![image](https://user-images.githubusercontent.com/17849068/108832947-84d3eb80-760f-11eb-95cd-520063af7796.png)
훈련이 계속 진행되는 이유는 일단 inputs.shape[0]==0을 만족시키지 못해 조건문 안으로 못들어가서 반복이 되는것같은데
이를 어떻게 해결해야할까요?

**Comment by sooftware** [comment]
실행환경이 어떻게 될까요?

**Comment by miziworld** [comment]
ubuntu18.04 docker 환경이고 cuda 10.1 그래픽카드 2080 1개 사용중입니다.
올린 사진에서 num_workers를 프린트출력했을때는 4로 나옵니다.

**Comment by sooftware** [comment]
음 아마 데이터 중 깨진게있어서 스레드 한 개가 죽었을 것 같네요.

**Comment by miziworld** [comment]
데이터중 어떤부분이 깨졌는지 알수없어서 다시한번 다운받아서 진행해보겠습니다.  혹시 스레드 수를 감소하는것말고는 지정한 스텝수만큼 지나면 다음 에포치로 넘어가게 코드수정할수는 없을까요?

**Comment by miziworld** [comment]
찾아보니 kspon폴더안에 pcm파일이 깨진게 몇개 있어서 발생했던 문제인것 같습니다. 그래서 깨진 데이터들을 제거하고 예를들면 KsponSpeech_01/KsponSpeech_0001/에 있는 데이터들과 그에 해당하는 transcripts.txt만 가지고 훈련시키려고 했습니다. 그런데 data load를 할때 
![image](https://user-images.githubusercontent.com/17849068/108989410-e744ee80-76d8-11eb-9248-05505ed97fa3.png)
이런식으로 전체 KsponSpeech 데이터를 찾는것같은데 data_path와 audio_path를 합쳐주면서 생기는 문제인것 같은데 audio path 경로를 제가 사용하는 폴더내로 지정하려면 어디서 어떻게 바꿔줘야할까요?
항상 빠른답변 감사합니다.
