### ISSUE TITLE
inputs.shape[0]==0 의미

### ISSUE THREAD

**Issue by miziworld** [sooftware/kospeech#116]
저번에 말씀주신것처럼 epoch가 계속 돌아가는 이유는 파일경로중에 깨진 pcm파일이 있어서였습니다.
이를 해결하고 다시 트레이닝을 돌리는데 supervised_trainer.py 중에 
![image](https://user-images.githubusercontent.com/17849068/109267820-8a1e7980-784d-11eb-8110-dafa448441c5.png)
에서 볼수있듯이 if inputs.shape[0]==0 부분에서 num_workers를 하나씩줄여가는데 이부분이 실행되지 않는것같아서 문의드립니다.
inputs.shape[0]은 어떤것을 의미하는것이며 언제 0이 되는지 여쭤보고 싶습니다.

그리고 훈련이 잘 되지않은 상태에서 inference.py를 실행시켰을 시 저는 공백으로만 나오는데 이것이 맞나요 아니면 이상한 한글로라도 결과물이 출력되는게 맞는건가요?

**Comment by sooftware** [comment]
거의 학습이 진행되지 않았다면, 다 공백으로만 나올 수도 있습니다. 각 스레드가 할당받은 데이터를 모두 로딩하게 되면 `num_workers` 변수를 하나씩 줄여나가고, 0이 되면 while 문이 종료되는 구조입니다.
