### ISSUE TITLE
lr_schedular관련 문의

### ISSUE THREAD

**Issue by switiz** [sooftware/kospeech#118]
## Title
lr_schedular관련 문의

## Description
본 git에서 제공해주시는 기능이 다양하고 많기 때문에 저에겐 이해하기 어려운 부분들이 있어서 모델 바이 모델로 분리하여 로그를 찍으면서 공부하고 있습니다.

단순한 형태로 Deepspeech2 모델을 분리하여 Train시 AIHUB전체 데이터를 학습해도 CER이 별달리 나아지지 않아
많은 좌절과 여러 가지 실험을 통해 lr_schedular 유무에 따른 성능 차이가 확연함을 확인하였습니다.

질문사항

lr_schedular를 사용 하신이유? https://github.com/SeanNaren/deepspeech.pytorch 를 찾아보면 제가 찾지 못한걸수도 있겠지만... lr_schedular를 사용하지 않은것 같은데 혹시 별도로 deepspeech모델에 사용하신 이유가 있으신가요? 주석의 SpecAugment논문을 찾아보면 LAS모델 기준으로 설명이 되어있어서, LAS모델을 구현하시면서 함께 넣으신건지 아니면 deepspeech를 바닐라로 구현할때 train시 빠르게 수렴하지 않아서 이를 해결하시려고 넣으신건지 문의드립니다.

## Linked Issues
  
- resolved #

**Comment by sooftware** [comment]
최근 대부분에 많이 쓰이는 스케쥴러이고, 제 경험상 스케쥴링 해주는게 더 성능이 좋아서 추가했습니다.

**Comment by switiz** [comment]
답변 감사드립니다! 
closed 처리하도록 하겠습니다!
