### ISSUE TITLE
dataset 경로 문의드립니다

### ISSUE THREAD

**Issue by miziworld** [sooftware/kospeech#120]
안녕하세요, 데이터셋 경로에서 항상 문제가생겨 문의드립니다.

저번에 질문드렸던것처럼 훈련이 끝나지않고 계속되는 이유는 KsponSpeech_0001~0124 폴더내에 깨진 pcm 파일들이 있어서 그랬던것으로 확인되었습니다. 그래서 깨진파일이 없는 폴더를 지정해서 training을 훈련시키고 싶은데 
예를들어 KsponSpeech_0001~0124파일이 아닌 0025폴더만 사용하고싶어서
python3 ./bin/main.py model=conformer-small train=conformer_small_train train.dataset_path=~~/KsponSpeech_0025/ 이런식으로 입력하면 

![image](https://user-images.githubusercontent.com/17849068/110606507-9996ae80-81cd-11eb-9da6-f4a65e31590c.png)
이런식으로 뒤쪽에 어떠한 경로가 더 붙어서 0001번에있는 audio부터 찾는것같습니다.
이를 절대경로로 어떻게 지정해주어야할지, 또는 0025파일안에 있는 audio파일 number를 어떻게 지정해주어야할지 도움을 주시면 정말 감사할것같습니다.

**Comment by sooftware** [comment]
transcripts.txt 파일에서 0025 폴더만 사용하도록 나머지를 날리면 될 것 같네요.
