### ISSUE TITLE
transformer inference 오류

### ISSUE THREAD

**Issue by miziworld** [sooftware/kospeech#124]
안녕하세요,
Transformer 모델을 사용해서 학습을 진행시켰고 만들어진 모델로 inference를 진행하려고 합니다

![image](https://user-images.githubusercontent.com/17849068/113557964-d07bab00-9639-11eb-9e21-d43be3fa361e.png)

전에 다른분이 질문주신것처럼 y_hats =  model.greedy_search 부분에서 오류가 발생하여 
greedy_search를 recognize로 변경하고 실행시키면

![image](https://user-images.githubusercontent.com/17849068/113558114-0b7dde80-963a-11eb-8c4f-ae661e3de90a.png)

이러한 에러가 뜹니다.
혹시 해결방법이 있을까요?

**Comment by dudgns0908** [comment]
[KoSpeech/kospeech/models/transformer/decoder.py](https://github.com/sooftware/KoSpeech/blob/latest/kospeech/models/transformer/decoder.py) 파일을 확인해보시면 아래와 같은 함수가 있습니다.  

```python
def decode(self, encoder_outputs: Tensor, encoder_output_lengths: Tensor) -> Tensor:
        batch_size = encoder_outputs.size(0)

        predictions = encoder_outputs.new_zeros(batch_size, self.max_length).long()
        predictions[:, 0] = self.sos_id

        for di in range(1, self.max_length):
            step_outputs = self.forward(predictions, encoder_outputs, encoder_output_lengths)
            step_outputs = step_outputs.max(dim=-1, keepdim=False)[1]
            predictions[:, di] = step_outputs[:, di]

        return predictions
```

해당 문제가 나타나는 이유는 예측되는 결과의 크기가 di의 값보다 작기 때문에 나타나는 현상입니다.
즉, 코드에서 step_outputs의 크기가 di의 값보다 작기 때문에 나타나는 에러입니다.  
정답이 되진 않겠지만 아래와 같이 수정하시면 에러는 없어질 것이라고 생각되네요

```python
def decode(self, encoder_outputs: Tensor, encoder_output_lengths: Tensor) -> Tensor:
        batch_size = encoder_outputs.size(0)

        predictions = encoder_outputs.new_zeros(batch_size, self.max_length).long()
        predictions[:, 0] = self.sos_id

        for di in range(1, self.max_length):
            step_outputs = self.forward(predictions, encoder_outputs, encoder_output_lengths)
            step_outputs = step_outputs.max(dim=-1, keepdim=False)[1]
            if step_outputs.shape[1] <= di:
                break

            predictions[:, di] = step_outputs[:, di]

        return predictions
```

**Comment by sooftware** [comment]
답변이 많이 늦었네요. 제가 확인해보고 수정을 해야하는데, 최근 일이 바빠서 신경을 못 쓰고 있네요. 한동안은 신경을 못 쓸 것 같습니다. 죄송합니다.

**Comment by miziworld** [comment]
@dudgns0908  감사합니다 덕분에 문제해결되었습니다
