### ISSUE TITLE
no module named 'kospeech.models.model'

### ISSUE THREAD

**Issue by miziworld** [sooftware/kospeech#126]
전에 main.py 실행시켰을때는 이런오류가 안떴었는데 새로 업데이트된 코드들 이용하니 갑자기 이러한 에러가 뜨네요
![image](https://user-images.githubusercontent.com/17849068/114386916-cecb5d80-9bcc-11eb-93d0-98ac0567f685.png)
어느 부분을 수정해야할까요..?

**Comment by sooftware** [comment]
음 제가 확인하고 있는데, 왜 에러가 나는지 아리송하네요. 혻시 지금도 에러가 나실까요?

**Comment by miziworld** [comment]
넵 환경을 바꿔서 다시해봐도 똑같은 에러가 발생하네요 ㅠㅠ

**Comment by sooftware** [comment]
해당 폴더에서 `pip install -e .` 실행 후에 해보실래요?

**Comment by miziworld** [comment]
앗 제가 프로젝트를 새로만들면서  그과정을 빼뜨렸네요 감사합니다.
