### ISSUE TITLE
깨진 KsponSpeech pcm 파일 pass 방법

### ISSUE THREAD

**Issue by miziworld** [sooftware/kospeech#127]
안녕하세요, 항상 빠른 답변 감사드립니다. 
얼른 저도 이프로젝트를 완성해서 더이상 질문드려서 번거롭게 하는일이 없었으면 좋겠네요 ㅠㅠ

저번에 말씀드렸던것처럼 Kspon dataset을 통째로 사용하다보면 중간에 깨진 pcm파일들이 있어서
쓰레드가 0으로 줄지 않아 Epoch 0에서 넘어가지 못하고 계속해서 반복되는 현상이 발생하였습니다.

깨진 pcm파일들을 하나씩 확인하여 transcripts.txt에서 제거할수는 있지만 너무 데이터양이 많다보니 수작업으로 진행하기에는 무리가 있습니다. 혹시 코드상에서 깨진 파일이 존재했을때 pass할 수 있는 코드를 추가할수 있을까요?

그리고 혹시 KsponSpeech 데이터셋 기준으로 어느정도 트레이닝을 돌렸을때 만족할만한 결과가 나오셨을까요?

**Comment by sooftware** [comment]
원하시는대로 실행될지는 장담은 못하겠지만 제가 data_loader.py쪽을 일부 수정해봤습니다.   
시도해보시고 문제 있으시면 문제나는 로그 첨부해주시면 또 수정해보겠습니다.

**Comment by sooftware** [comment]
혹은 파이썬 스크립트 하나 짜셔서 모든 pcm 파일을 로드해보시면서 에러나는 경로를 모두 기록해두었다가 transctips.txt에서 해당 경로를 제외하시는것도 방법이에요.
