### ISSUE TITLE
Checkpoint defect in supervised_trainer.py

### ISSUE THREAD

**Issue by kelvinqin** [sooftware/kospeech#130]
## Title
- Checkpoint defect in supervised_trainers.py

## Description
line 190: Checkpoint(model, self.optimizer, self.criterion, self.trainset_list, self.validset, num_epochs).save()

should be:
 Checkpoint(model, self.optimizer, self.trainset_list, self.validset, num_epochs).save()

## Linked Issues
  
- resolved #

**Comment by sooftware** [comment]
Oh, Thank you!
