### ISSUE TITLE
recognize bug report

### ISSUE THREAD

**Issue by kelvinqin** [sooftware/kospeech#131]
## Title
- recognize bug report

## Description
In kospeech/models/model.py (line 92), recognize function only fetch the probs without sequence length information:

**predicted_log_probs, _ = self.forward(inputs, input_lengths)**

I think this is wrong because inside a batch, difference utterance will have different output length, you should truncate the predicted_log_probs accordingly for metric to calculate a correct CER.

Not sure if I am wrong? But thanks for you to take a look.

## Linked Issues
  
- resolved #

**Comment by kelvinqin** [comment]
I noticed that in label_to_string function you will make a decision about the end of the prediction by checking whether there is a <eos>, this is reasonable for seq2seq model, but for CTC model like deepspeech2, not sure if it is reasonable.

Thanks for your sharing,

**Comment by sooftware** [comment]
Hi @kelvinqin. The CTC model does not require output_length.You can decode it using <eos>, <blank>.
