### ISSUE TITLE
repetition_remove in CER calculation for CTC model

### ISSUE THREAD

**Issue by kelvinqin** [sooftware/kospeech#133]
## Title
- repetition_remove in CER calculation for CTC model

## Description
Usually, CTC model will generate some character repetition, I did not see any repetition removing when you calculate CER, Please see this is another defect,

Thanks!

## Linked Issues
  
- resolved #

**Comment by sooftware** [comment]
Check https://github.com/sooftware/KoSpeech/blob/4d8ddf1322b99f704af92d3e15c274c96972a801/kospeech/vocabs/ksponspeech.py#L78
