### ISSUE TITLE
pre trained 모델 다시 업로드 하셨나요?

### ISSUE THREAD

**Issue by Alcoholrithm** [sooftware/kospeech#135]
제가 사용하는 환경에 적합한지 간단히 테스트 하고 싶은데 보이지가 않네요 ㅜㅜ
1월 말에 전반적인 refactoring 후에 올리신다고 하셨는데, 제가 못 찾는건가요
아무리 찾아봐도 보이지가 않네요 ㅜㅜ

**Comment by sooftware** [comment]
제가 개인적으로 일이 바빠서 학습을 못하고 있습니다. ㅠ.ㅠ

**Comment by Alcoholrithm** [comment]
앗 일찍 답변하신걸 알람을 못 봤네요 ㅜㅜ
모쪼록 바쁘신일 해결되길 바랍니다!
