### ISSUE TITLE
Can you provide some pre-trained model?

### ISSUE THREAD

**Issue by ZhangDongyuCN** [sooftware/kospeech#136]
## Title
- Can you provide some pre-trained model?

## Description
Training this model requires a large number of data sets, which is difficult to train. Can a pre-trained model be provided? I need a Conformer model with LibriSpeech dataset. And, I need this model exprot to onnx, but this can do by myself.

**Comment by sooftware** [comment]
I have no plan to train LibriSpeech with KoSpeech now. But I'm going to train LibriSpeech using [this repo](https://github.com/sooftware/lightning-asr).

**Comment by ZhangDongyuCN** [comment]
Do you have pre-trained Conformer model with other dataset ? It it still ok for me. Now I just need a pre-trained Conformer model, whatever the dataset.

**Comment by sooftware** [comment]
I trained conformer in Korean before, but the model code is very different from now, so you won't be able to use it.

**Comment by ZhangDongyuCN** [comment]
> I trained conformer in Korean before, but the model code is very different from now, so you won't be able to use it.

Is the new code in this repo [sooftware/conformer](https://github.com/sooftware/conformer)? Can you provide the source code and ckpt model, which you used to train Conformer?

**Comment by sooftware** [comment]
Yes, a little bit different. Unfortunately I have no source code I tranined. You have to train. Sorry.
