### ISSUE TITLE
LAS Training 시에 생기는 shape 관련 Runtime Error

### ISSUE THREAD

**Issue by sausage-333** [sooftware/kospeech#140]
## Title
- 

## Description
Joint CTC-LAS 모델을 깃헙에 제시된 config 그대로 실험을 돌렸으나, shape 문제가 있어 실험이 되지 않습니다.

다른 이슈를 보니 Multi-gpu Processing이 지원이 안돼 그런 것일수 있다고 합니다만,

확실히 여쭤보기 위해 에러 로그를 함께 첨부합니다.

![egvdf](https://user-images.githubusercontent.com/54805233/119315666-0ee42c80-bcb1-11eb-9ff6-b14068081624.PNG)

더하여, 훈련 config를 변경하기 위해 configs/train의 las_train.yaml을 변경하였는데요.

![fdgv](https://user-images.githubusercontent.com/54805233/119315829-389d5380-bcb1-11eb-9667-cdaba6657b0b.PNG)

위처럼 Indentation이 끝난 이후에만 수정된 config로 된 것을 확인할 수 있었습니다.

train: 이후의 내용을 바꾸기 위해서는 어떻게 해야하는지, 관련해서 코드 내부적인 내용을 간단히 설명해주실 수 있는지요.

감사합니다.

## Linked Issues
  
- resolved #

**Comment by sooftware** [comment]
안녕하세요. 위 에러는 제가 시간이 날때 살펴보고 코멘트 드리겠습니다. 최근 KoSpeech에 이런저런 에러가 많아서 좀 더 많은 기능과 쉬운 사용법의 라이브러리를 개발중이고 이번주 혹은 다음주 정도  공개 예정이라 kospeech는 신경을 잘 못 쓰고 있네요. ㅠ.ㅠ 급한게 아니시라면 1-2주 정도만 기다려주시면 더 편하게 학습 가능하실 것 같습니다.
