### ISSUE TITLE
BeamDecoderRNN 에러

### ISSUE THREAD

**Issue by miziworld** [sooftware/kospeech#142]
![image](https://user-images.githubusercontent.com/17849068/120467202-e0fe9680-c3da-11eb-90da-2ece4b299fc3.png)

안녕하세요, 최근에 업로드해주신 코드로 joint-ctc-attention-transformer 수행시키려고 할때
beamDecoderRnn을 찾지못하는 에러가 발생하네요...
__init__.py에 클래스선언은 제대로 되어있고 models 안에 beam_search.py도 존재하는데 어떻게해결해야할까요 ..? ㅠㅠ

그리고 /KoSpeech/kospeech/models/las/beam_search_decoder.py 파일이 존재는 하지만 비어있는데 맞는건가요?

**Comment by sooftware** [comment]
빔서치쪽 로직을 방금 좀 수정했습니다. 확인해주세요.

**Comment by matthewoots** [comment]
Hi there, sorry to raise this issue again, even with @sooftware change in logic for `beam_search_decoder.py`, I am still facing the same import issue
```
Traceback (most recent call last):
  File "./bin/main.py", line 26, in <module>
    from kospeech.model_builder import build_model
  File "/home/matthew/KoSpeech/kospeech/model_builder.py", line 20, in <module>
    from kospeech.models.conformer import Conformer
  File "/home/matthew/KoSpeech/kospeech/models/__init__.py", line 32, in <module>
    from kospeech.models.las.decoder import DecoderRNN, BeamDecoderRNN
ImportError: cannot import name 'BeamDecoderRNN' from 'kospeech.models.las.decoder' (/home/matthew/KoSpeech/kospeech/models/las/decoder.py)
```

**Comment by sooftware** [comment]
Hi @matthewoots. This repository is archived. Further development is underway [here](https://github.com/openspeech-team/openspeech).

**Comment by matthewoots** [comment]
Thank you so much @sooftware . Will give it a visit! :+1:

**Comment by popohot2002** [comment]
> Thank you so much @sooftware . Will give it a visit! 👍

did you solve this problem? I faced the same problem as you.

**Comment by sooftware** [comment]
@popohot2002 I recommend you to visit https://github.com/openspeech-team/openspeech/

**Comment by rcheol** [comment]
안녕하세요!
저도 @miziworld 님과 같은 문제를 겪고 있습니다. 
kospeech 대신 openspeech 를 사용하면 해결되는 문제인가요?

**Comment by sooftware** [comment]
네
