### ISSUE TITLE
if문의 불필요한 인자인지 궁금합니다

### ISSUE THREAD

**Issue by GeunHyeong-Jo** [sooftware/kospeech#143]
## Title
- if문의 불필요한 인자인지 궁금합니다

## Description
![image](https://user-images.githubusercontent.com/52905047/120733362-fa5e2a80-c521-11eb-81b3-3b6d0aa4251e.png)
KoSpeech/bin/main.py에서 80번째줄의 if문에서 config.train.num_threads와 int(config.train.num_threads)가 동일한것 같은데 굳이 and를 사용할 필요가 있는지 궁금합니다.
## Linked Issues
  
- resolved #

**Comment by sooftware** [comment]
컨트리뷰터분이 수정해주신 코드인데, 아마 추측하기로는 num_threads 변수가 있으면 0보다 큰지 체크하려고 만든 것 같네요.
