### ISSUE TITLE
Jasper model에 관심이 있어 학습을 진행하였는데 오류가 발생합니다.

### ISSUE THREAD

**Issue by heeyong-park** [sooftware/kospeech#144]
1. jasper 10x5 model에 관심이 있어 학습 중 아래와 같은 오류가 발생하여 질문드립니다.
   1) Calculated padded input size per channel: (55). Kernel size: (57). 
       Kernel size can't be  greater than actual input size
        a)  super(MaskConv1d, self) <bound method Conv1d.forward of 
             MaskConv1d(768, 896, kernel_size=(29,), stride=(1,), dilation=(2,), bias=False)>
              - MaskConv1d(768,896) layer에서 error 발생 
   2) CTC Loss Nan 발생 --> outputs에서 Nan 발생

**Comment by sooftware** [comment]
넣어주신 인풋 길이가 convolution 커널사이즈보다도 작게 들어가서 생긴 에러 같습니다. 넣어준 인풋 오디오가 혹시 너무 짧은건 아닌지 체크해주세요. 그리고 https://github.com/sooftware/OpenSpeech 을 이용해서 학습하는 것을 추천드립니다.
