### ISSUE TITLE
Any pre-trained model provided?

### ISSUE THREAD

**Issue by sally-yuan** [sooftware/kospeech#146]
## Title
- 

## Description
Hi, will there be any pre-trained model provided? Please let me know if you plan to upload one.

## Linked Issues
  
- resolved #

**Comment by sooftware** [comment]
Unfortunately, we don't provide pre-train model.

**Comment by sooftware** [comment]
Check https://github.com/SoftwareImpacts/SIMPAC-2020-63

**Comment by henry8904** [comment]
> Check https://github.com/SoftwareImpacts/SIMPAC-2020-63

좋은 코드 감사합니다. 
링크 걸어주신 곳에 Pre-trained Model 링크를 들어가보면 요청하신 파일이 존재하지 않는다고하는데...
더이상 이용은 불가능한가요?

**Comment by Aksh97** [comment]
> Check https://github.com/SoftwareImpacts/SIMPAC-2020-63

Hi, the model is not available, are they deleted?

**Comment by Aksh97** [comment]
@sally-yuan, do you have the downloaded model?

**Comment by sooftware** [comment]
See https://github.com/sooftware/kospeech/issues/154
