### ISSUE TITLE
pre-trained model 질문드립니다!

### ISSUE THREAD

**Issue by YooSungHyun** [sooftware/kospeech#149]
## Title
- pre-trained model이 git에 현재 있는 건가요? 또한 컨피그도 궁금합니다.

## Description
링크는 일단 [페이스북 아티클 링크](https://www.facebook.com/groups/TensorFlowKR/posts/1265237693817286/) 를 타고 들어왔습니다.
현재 깃에보면 프리트레이닝 모델이 없는 것 같은데 어디서 받을 수 있을까요?
그리고 모델의 경우 16kHz용인지, 8kHz용인지도 궁금합니다. (아마 AIHub Ksponspeech가 16kHz 기반일거라 16kHz기반이긴 할테지만요...)

혹시 8kHz로 구축해보신 경험이 있거나 하다면 결과가 어땠는지도 좀 궁금합니다.

**Comment by YooSungHyun** [comment]
kospeech는 이제 뭔가 지원이 중단되려나 보네요....따흐흑

**Comment by sooftware** [comment]
답변이 너무 많이 늦어 죄송합니다!
프리트레인 모델의 경우 모델 아키텍처 변화가 많아져서 제공하는 프리트레인 모델이 의미가 없어져서 더 이상 제공하지 않게 되었습니다 ㅎㅎ..
16kHz이며, 8kHz로 해본 경험은 없습니다.
