### ISSUE TITLE
kspon dataset에서 inference를 실행할 때 train 데이터는 결과값이 나오고, eval 데이터는 결과값이 나오지 않습니다.

### ISSUE THREAD

**Issue by woojjn** [sooftware/kospeech#158]
## Title
- kspon dataset에서 inference를 실행할 때 train 데이터는 결과값이 나오고, eval 데이터는 결과값이 나오지 않습니다.

## Description
kspon dataset에서 inference를 실행할 때 train 데이터는 결과값이 나오고, eval 데이터는 결과값이 나오지 않습니다.

Traceback (most recent call last):
  File "./bin/inference.py", line 56, in <module>
    feature = parse_audio(opt.audio_path, del_silence=True)
  File "./bin/inference.py", line 37, in parse_audio
    waveform=Tensor(signal).unsqueeze(0),
TypeError: new(): data must be a sequence (got NoneType)

eval 데이터에서만 np.memmap(audio_path)가 None 값을 return하는데 그 이유를 모르겠습니다.

+ 추가적으로, 직접 녹음한 음성을 inference 했을 때도 train 만큼의 성능이 나오지 않았는데, 그 이유를 혹시 알 수 있을까요?

## Linked Issues

  
- resolved #

**Comment by kthworks** [comment]
첫번째 질문에 대해서는, encoding문제로 load_audio 함수 안에 있는 np.memmap 함수에서 예외처리가 되어 NoneType이 반환되는 것 같습니다.  eval에 있는 데이터를 메모장으로 여신 후에 ANSI encoding 형식으로 맞추신 후 다른이름으로 저장하신 후 inference 해보시면 인퍼런스가 가능합니다! ㅎㅎ (처음 파일을 열때도 ANSI로 인코딩이 되어있는 것 같은데, 왜 문제가 생기는지는 저도 잘 모르겠습니다 ^^;; )

두번째 질문에 대해서는, 모델은 train data를 기반으로 학습되었으므로 당연히 직접 녹음하신 음성보다는 kspon dataset에 더 최적화된 결과를 냅니다. 모델은 kspon dataset만 보고 배웠으니까요. train 만큼의 성능이라고 하신 것이 train accuracy를 말씀하신건지 validation accuracy를 말씀하신건지 모르겠지만, 직접 녹음하신 음성 파일의 경우는 third-party data에 해당하므로 eval에 있는 ksponspeech data를 test로 썼을 때보다 더 좋은 성능을 기대하기는 어려울 것 같습니다. (ksponspeech dataset의 test데이터는 모델이 한번도 본 적이 없긴 하지만 train data와 비슷한 구석이 많지만,  직접 녹음하신 파일은 훨씬 다르니까요.)

**Comment by woojjn** [comment]
third-party data가 잘 안됐던 것이 성능이 안 나온다기 보단 정말 이상한 값이 나왔다고 표현했어야 했는데 전달을 잘못했네요. 제가 녹음한 음성 결과가 "아 오 어" 이런 식으로 나와서 물어봤던 거고, 결과적으로 csv 파일 경로를 제대로 설정해줘서 해결했습니다. 답변 주셔서 감사합니다.
