### ISSUE TITLE
학습시 GPU 메모리크기

### ISSUE THREAD

**Issue by mnbv7581** [sooftware/KoSpeech#17]
어떤 스펙의 GPU를 사용해서 학습하셨는지 알 수 있을까요? 현재 2080ti 모델로 학습시에 배치크기를 8로 설정해도 OOM 에러가 발생합니다.

**Comment by sooftware** [comment]
저 같은 경우는 GTX TITAN X 4대로 구성된 서버를 사용하요 있습니다.    
KsponSpeech 데이터에 길이가 긴 오디오가 있어서 학습이 잘 되다가도 OOM이 자주 뜨더라구요.   
그래서 저희는 너무 길다고 판단되는 데이터들은 학습에서 제외하고 학습시켰습니다.  
해당 데이터리스트는 data/data_list/filter_train_list.csv 에 파일 목록이 있습니다.  
  
더 궁금하신 점 있으면 언제든지 이슈 남겨주세요.

**Comment by sooftware** [comment]
추가적으로 GTX TITAN X 1대로 구성된 로컬 데스크탑에서는 filter_train_list.csv에 저장된 파일들로 학습시, 배치사이즈 12까지는 무난하게 학습되었습니다.

**Comment by mnbv7581** [comment]
설명 감사합니다. 참고해서 실행해보겠습니다.

**Comment by sooftware** [comment]
아 그리고 최근 코드가 많이 바뀌면서 여러 버그사항들이 있었는데,  현재는 해결 했습니다.    
언제 버젼을 사용하고 계신지는 모르겠지만 최신으로 다시 다운받으셔서 하시는게 좋을 것 같습니다 !!
