### ISSUE TITLE
패키지 설치 오류

### ISSUE THREAD

**Issue by yoloo795** [sooftware/kospeech#170]
## Title
- 패키지 설치 오류

안녕하세요.

torchaudio: pip install torchaudio==0.6.0 (Refer [here](https://github.com/pytorch/pytorch) for problem installing torchaudio)
를 실행하였을 때 0.6.0 버전이 존재하지 않아 가장 낮은 버전인 0.8.0을 설치하였습니다.
설치 후 warp_rnnt 패키지 설치 시도 중 Winerror 127이 나오면서 dll이 존재함에도 인식을 못해 설치가 진행되지 않았습니다.

구글에서 찾아본 결과 pytorch 1.5.1 이하의 버전부터 winerror 127을 해결 할 수 있다고 하는데 혹시 0.6.0을 설치 할 수 있는 방법이나 다른 해결방법이 있을까요?

**Comment by Silentssss** [comment]
![image](https://user-images.githubusercontent.com/108161275/203509919-da53a4b6-c130-4863-a109-b4bfebfbfa1b.png)
![image](https://user-images.githubusercontent.com/108161275/203510081-8efed622-cdd4-458f-bd1e-c47ca66f49b9.png)
That is my torch、cuda、torchaudio version, you can try it. I am a Chinese, but I can not download the KsponSpeech dataset which is in your Korea. Can you send it to my email(xjl1263780481@163.com)? Thank you!

**Comment by XEL-Maker** [comment]
지나가던 사람입니다. 
라이브러리 설치에 앞서서 cuda 와 cudnn 설치를 합니다.
저는 11.6버전을 설치했습니다. 
저는 아나콘다로 파이썬 3.7버전에 아래의 명령어로 설치를 하였습니다. 
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2 -c pytorch
pip install warp_rnnt
pip install torchaudio==0.6.0
여기서 파일 pip install warp_rnnt에서 오류가 발생할수 있습니다.
저는 RTX A4000이라 8.6으로 오류가 발생하여 제일 마지막 오류의 파일 1414번째줄에서 조금 위로 올라가면
나오는 호환성 리스트에 8.6을 작성해서 통과시켰습니다.
warp_rnnt가 보증된것은 10.1까지인것으로 알고있어서 저는 일부러 저렇게 셋팅을 햇습니다.

**Comment by XEL-Maker** [comment]
추가로 방금전 pytorch를 최신버전으로 업데이트하니 정상작동(gpu 사용률도 올라갑니다.)은하지만
제가 가지고있는 그래픽카드로는 배치사이즈 8을 감당하진 못하네요...
