### ISSUE TITLE
빔서치 디코딩 에러

### ISSUE THREAD

**Issue by mnbv7581** [sooftware/KoSpeech#22]
빔서치 사용해서 모델평가를 진행하면 이러한 에러가 발생합니다. 원인이 무엇인지 알 수 있을까요?
실행옵션은 decode 옵션을 greedy -> beam 으로만 바꿔주어서 그대로 실행하였습니다

![빔서치에러](https://user-images.githubusercontent.com/44501825/84620548-467c1d80-af13-11ea-8d48-f0c1986e81c9.jpg)

**Comment by sooftware** [comment]
![image](https://user-images.githubusercontent.com/42150335/84644089-a2f23380-af39-11ea-897a-afe9819fb36b.png)
  
위와같이 self.decoder = decoder 를 추가해주시면 될 것 같습니다.  
코드 수정 과정에서 빠트린거 같습니다. 수정하여 push 하겠습니다.  
  
감사합니다.
