### ISSUE TITLE
외부 언어모델 통합관련

### ISSUE THREAD

**Issue by ilwoonam75** [sooftware/KoSpeech#23]
안녕하세요 
좋은 소스 감사합니다 
Readme에서 언급하신 외부 언어모델이 어떻게 활용되고 있는지 궁금하여 글을 남깁니다. 설명 부탁드립니다.

**Comment by triplet02** [comment]
안녕하세요, Kai.Lib 팀의 배세영입니다.
저희는 별도로 학습시킨 자체 언어 모델을 사용하고 있습니다. 관련 내용은 [여기](https://github.com/sooftware/char-rnnlm) 혹은 [여기](https://github.com/sooftware/KoSpeech/blob/master/kospeech/model/lm.py)를 참고해 주세요.

예를 들어 "안녕하세요, 반갑습니다." 라는 발화 시퀀스를 예측하는 도중의 어떤 timestep T에 대하여, T-1번째 timestep까지의 output들을 모두 (ex, "안녕하세요, 반갑") 언어모델의 input으로 넘겨주어 언어모델의 T번째 output을 얻습니다. 그리고 음향모델이 예측한 T번째 timestep의 output을 얻고, 적절한 weight를 취하여 둘을 합산하는 방식으로 최종적인 T번째 output text를 얻게 됩니다.

자세한 내용은 [Decoder.py](https://github.com/sooftware/KoSpeech/blob/master/kospeech/model/decoder.py) 파트에서 forward 도중, use_external_lm 조건 체크 부분을 보시면 좋을 것 같습니다.

**Comment by ilwoonam75** [comment]
설명 감사드립니다.

설명해주신 내용을 바탕으로 분석을 해보았는데, 소스상으로는 use_external_lm부분이 되어 있는데,
현재 Decoder.py 구현에는 language_model=None이라, 해당 분기를 타지 않는 것으로 이해가 됩니다..

제가 잘못 이해한것인지요?

**Comment by sooftware** [comment]
language_model=None으로 설정해둔 것은, 디폴트 값일 뿐입니다.    
해당 파라미터에 언어모델을 넘겨주지 않으면 해당 분기는 타지 않겠지만, 넘겨주게 되면  
None이 아닌 언어모델로 설정이 됨으로써 if 문을 통과하게 됩니다.  
   
해당 부분은 파이썬의 디폴트 파라미터 설정하는 방법에 대해 공부해보시면 궁금증이 풀리실 것이라 생각됩니다.

**Comment by ilwoonam75** [comment]
설명 감사드립니다.
한가지만 더 여쭤보겠습니다.
1. 그럼 현재 CRR 값 등은 언어모델을 포함하여 측정을 한것인지와
2. 사용하셨다면 테스트 가능한 사전 학습된 언어모델이 있을까요?

**Comment by triplet02** [comment]
Readme를 통해 알려드린 최고  CRR 기록은 언어모델을 사용하지 않고 달성한 것입니다.
저희도 현재 다양한 방식으로 언어모델 활용을 시도해 보고 있는 중이라, 테스트 해 보실만한 언어모델은 아직 완성되지 않은 상황입니다.

**Comment by ilwoonam75** [comment]
빠른 답변 감사드립니다.
