### ISSUE TITLE
How we can train languages other than Korean? 

### ISSUE THREAD

**Issue by usamaehsan** [sooftware/KoSpeech#31]

**Comment by sooftware** [comment]
If you have dataset (audio & transcript), You can train, but you have to modify a few things.  
  
1. First, you should make a character label like [this](https://github.com/sooftware/KoSpeech/blob/master/data/label/aihub_labels.csv).  
2. Second, you have to convert transcripts to ids on character labels.  
3. The code should be modified considering the structure of the dataset. (You will need to modify the kospech/data directory.)  
  
If you have any other questions, please leave an issue at any time.

**Comment by usamaehsan** [comment]
@sooftware can you please tell whats freq in aihub_labels.csv?

**Comment by sooftware** [comment]
Freq is not very important. Freq (frequency) is a count of how often it appeared in a dataset.    
Freq is not used in training, so you don't have to worry.

**Comment by usamaehsan** [comment]
thanks,you are very helpful
i am new to this feild and there is no speech recognition available for my language urdu thats why i am trying to build urdu speech recognition system using this repo

**Comment by sooftware** [comment]
It's a great honor. I want to help you as much as I can, so please leave an issue or contact me at sh951011@gmail.com at any time.  
During the week, I may be busy and answer late, but I will answer as soon as possible on the weekend.

**Comment by usamaehsan** [comment]
thanks
