### ISSUE TITLE
CPU 기반 학습 가능 여부

### ISSUE THREAD

**Issue by minlom** [sooftware/KoSpeech#39]
안녕하세요, 
해당 코드를 학습시에 GPU 이슈가 계속해서 발생하여 CPU 기반으로 코드를 기동하려고 파라미터를 조정하였는데 
학습 진행이 안됩니다.
CPU로는 학습이 불가한지요?

- 설정 내역
utils.py

def check_envirionment(use_cuda):
    """
    Check execution envirionment.
    OS, Processor, CUDA version, Pytorch version, ... etc.
    """
    cuda = use_cuda and torch.cuda.is_available()
    #device = torch.device('cuda' if cuda else 'cpu')
    device = torch.device('cpu')
    print("cuda : ", cuda)
    logger.info("Operating System : %s %s" % (platform.system(), platform.release()))
    logger.info("Processor : %s" % platform.processor())

**Comment by sooftware** [comment]
cpu로 몇 가지 수정을 하게 되면 학습이 가능하겠지만, GPU로도 오래 걸리는 학습인지라, 사실상 학습이 불가능합니다.  
GPU 이슈를 해결하는게 나을 것 같습니다.

**Comment by minlom** [comment]
네 알겠습니다.
확인 감사합니다!
