### ISSUE TITLE
Pretrain Model

### ISSUE THREAD

**Issue by sooftware** [sooftware/KoSpeech#41]
현재 공개된 Pre-train 모델은 현재 폴더 구조에서 1에폭만 학습된 모델입니다.
이후 추가 학습이 되는대로 업데이트하여 공개하겠습니다.

**Comment by ur-luella** [comment]
안녕하세요. 매번 빠른 업데이트에 감사드립니다!
현재 오픈되어있는 model (2).pt는 사용해도 큰 이슈가 없는 걸까요??
감사합니다!

**Comment by sooftware** [comment]
음..아마요...? ㅎㅎ 안되면 말씀해주세요!

**Comment by ur-luella** [comment]
앗 그렇군요ㅎㅎ 감사합니다!!
