### ISSUE TITLE
Two issues about executing run_pretrain.sh & prepare_ksponspeech.sh

### ISSUE THREAD

**Issue by sausage-333** [sooftware/KoSpeech#45]
안녕하세요, 이렇게 좋은 자료를 Open으로 해주셔서 감사합니다. 많이 배우고 있어요.

코드를 자세히 살펴보기 시작한지는 얼마 되지 않았는데요, 초기 단계에서 에러가 발생하여 이슈 올려려요.

![1](https://user-images.githubusercontent.com/54805233/92110562-e0be7400-ee25-11ea-967b-ac94111655ce.PNG)

run_pretrain.sh의 코드를 진행할 때 new() 관련 Type 에러가 발생하구요.

![2](https://user-images.githubusercontent.com/54805233/92110563-e1efa100-ee25-11ea-8b3e-0eebc53527bc.PNG)

prepare_ksponspeech.sh의 코드를 진행할 때에는 Value 에러가 발생합니다.

두 가지 뭔가 간단한 것을 놓치고 있는 듯 한데, 제가 어떤 점을 간과하고 있는지 알 수 있을지요.

감사합니다!

**Comment by sooftware** [comment]
음 첫번째 문제는 오디오 파일 경로 설정 한번 해봐주세요!  
두 번째 문제는 지금 밖이라 들어가는대로 확인해보겠습니다 ㅎㅎ

**Comment by sooftware** [comment]
log를 보니까 preprocess 까지는 된 것 같은데, preprocess된 폴더 구조 한번 보여주실 수 있을까요?

**Comment by sausage-333** [comment]
> 음 첫번째 문제는 오디오 파일 경로 설정 한번 해봐주세요!

아, KsponSpeech 자료 필요하군요. 이건 ai hub 쪽에 요청해야할 것 같네요.


> log를 보니까 preprocess 까지는 된 것 같은데, preprocess된 폴더 구조 한번 보여주실 수 있을까요?

네.

![G3RWEF](https://user-images.githubusercontent.com/54805233/92207199-d3f05d80-eec3-11ea-8702-c847cca70576.PNG)

![3](https://user-images.githubusercontent.com/54805233/92207198-d2bf3080-eec3-11ea-9b75-4112a276fd58.PNG)

**Comment by sooftware** [comment]
아 KsponSpeech (AI Hub) 데이터셋을 따로 다운받지 않으신건가요??   
데이터셋을 다운 받으시고, 경로 설정을 해주셔야합니다.

**Comment by sausage-333** [comment]
두 문제 모두 Dataset을 다운 받고, 경로 설정을 해주면 되겠군요. 감사합니다!

**Comment by sooftware** [comment]
넵넵 ㅎㅎ 해보시다가 안되시면 또 이슈 남겨주세요.
