### ISSUE TITLE
Pre-train Model

### ISSUE THREAD

**Issue by sooftware** [sooftware/KoSpeech#53]
현재 Pre-train 모델을 학습하고 있습니다.  
빠른 시일내로 모델 파일을 업데이트 하겠습니다.

**Comment by junhahyung** [comment]
혹시 언제 완료될지 대략 알 수 있을까요? 감사합니다:)

**Comment by sooftware** [comment]
mfcc로 학습시킨 모델은 공개되어 있습니다.  
리드미를 참고해주세요
