### ISSUE TITLE
run_pretrain.py error

### ISSUE THREAD

**Issue by junhahyung** [sooftware/KoSpeech#55]
mfcc 로 학습된 pretrained  모델로 inference 를 하는 과정에서 지속적으로 dimension 에러가 발생합니다.

run_pretrain.py 의
model = load_test_model(opt, opt.device)
한 후 output = model( ... ) 에서,

구체적으로 models/las/encoder.py 의 97번째 줄에서 (output, hidden = self.rnn(conv_feat)) 해당 에러가 발생합니다.

<img width="719" alt="Screen Shot 2020-11-03 at 12 59 57 AM" src="https://user-images.githubusercontent.com/42991683/97890145-892e7d00-1d70-11eb-933f-571a72f19909.png">

무엇이 문제인지 모르겠네요..

**Comment by sooftware** [comment]
```python
import librosa

def parse_audio(audio_path: str, del_silence: bool = True) -> Tensor:
    signal = load_audio(audio_path, del_silence)
    mfcc = self.transforms(y=signal, sr=16000, n_mfcc=40, n_fft=320, hop_length=160)

    feature_vector -= feature_vector.mean()
    feature_vector = Tensor(feature_vector).transpose(0, 1)

    return feature_vector
```

run_pretrain.py의 parse_audio() 함수를 이렇게 수정해보실래요??  
run_pretrain.py의 피쳐는 fbank이고, 제가 공개한 모델은 mfcc 피쳐를 사용한 모델이라 피쳐 사이즈가 달라서 오류가 난 것 같네요

**Comment by junhahyung** [comment]
feature_vector 가 mfcc 를 의미하는 것이 맞나요?
self.transforms 로는 librosa.feature.mfcc 를 사용하면 되는걸까요?

그리고 sr, n_mfcc, n_fft, hop_length 등에 의해 결과가 달라지는 것 같은데, 저 세팅으로 사용하면 될까요? 현재는 결과가 잘 안나오네요,,
감사합니다:)

**Comment by sooftware** [comment]
어떤 데이터를 넣으셨나요?  
학습당시에 사용했던 파라미터로 옵션을 넣어준 것으로 기억합니다.  
  
아 변수명이 안 바뀌었네요 mfcc가 feature_vector 맞습니다

**Comment by junhahyung** [comment]
일단 테스트용을 일반 음성이 녹음된 .wav 파일을 사용했습니다. 음성의 길이가 5초정도 됩니다.

**Comment by sooftware** [comment]
완전히 뭉개진다면 샘플레이트를 확인해보시면 좋을 것 같네요.  
샘플레이트가 다르다면 당연히 잘 인식이 안될거에요

**Comment by sooftware** [comment]
아 의심되는게 하나 생겼는데, `input_reverse` 옵션으로 학습된 모델이라, 피쳐를 뒤집어줘야 할 것 같네요
