### ISSUE TITLE
run_pretrain.py Import error

### ISSUE THREAD

**Issue by HeonKK** [sooftware/KoSpeech#56]
안녕하세요. run_pretrain.py를 실행시키던 도중 import 에러가 발생하여 문의드립니다.

pre-trained 모델을 다운받은 상태이고, model_path, audio_path 경로지정까지 완료했습니다. 
input으로 pcm파일까지 지정해준 상태로 infer-with-pretrain.sh를 실행하니

ImportError: cannot import name 'label_to_string' from 'kospeech.utils' (../kospeech/utils.py)

위와 같은 에러가 발생하더군요. 찾아보니 label_to_string은 kospeech/vocab.py 아래 클래스 내부 함수로 존재하던데 혹시 해결할 수 있는 방법이 있을까요?

**Comment by sooftware** [comment]
답이 늦었네요. 이슈를 놓쳤습니다 ㅠ.ㅠ.  
말씀해주신 부분 수정해놨습니다.

**Comment by HeonKK** [comment]
감사합니다~

혹시 아래 csv파일은 어떤 내용이 들어있는건지 알 수 있을까요?? 따로 없는 것 같아서 이 부분도 문의드립니다.

vocab = KsponSpeechVocabulary('../data/vocab/aihub_vocabs.csv')

**Comment by sooftware** [comment]
해당경로 타고 들어가보시면 있을건데, 음.. 이상하네요

**Comment by HeonKK** [comment]
아아 그러네요.. 제가 어제 저 부분에서 임포트 에러를 보고 docs에서 한수를 따서 돌리고 있었던 차라 확인을 못했던 것 같습니다.
감사합니다!
