### ISSUE TITLE
pretrained model 실행방법에 대해서

### ISSUE THREAD

**Issue by MoongMoong** [sooftware/KoSpeech#59]
bin/run_pretrain.py
함수를 사용하면 모델의 테스트가 가능할거같아서

model을 다운받은 후 아래와 같이 경로를 지정하였는데 모델로드가 안되네요..
data.pkl파일이 아닌 다른 모델을 로드해야 하는건가요?
torch에 익숙하지 않아 기초적인 질문을 하게되어 죄송합니다.

parser = argparse.ArgumentParser(description='Run Pretrain')
parser.add_argument('--model_path', type=str, default='../archive/data.pkl')
parser.add_argument('--audio_path', type=str, default='../sample.wav')
parser.add_argument('--device', type=str, default='cuda')

**Comment by sooftware** [comment]
이슈를 놓쳤었네요. 늦은 답변 죄송합니다.  
다운받으신 파일 자체를 경로로 넘기시면 됩니다. Ex) `model.pt`  
  
얼핏 보기에 모델 파일 안쪽으로 들어가신 것 같아요.
