### ISSUE TITLE
샘플레이트 변경

### ISSUE THREAD

**Issue by mnbv7581** [sooftware/KoSpeech#61]
![input_size_error](https://user-images.githubusercontent.com/44501825/100968613-fc483080-3574-11eb-93d4-35365cc2de04.jpg)

샘플레이트 옵션을 8Khz로 설정한 후에 8Khz 데이터를 학습하고 싶습니다. 하지만 input_size 에러가 나오는데 따로 변경해야하는 옵션이나 소스가 있습니까?

**Comment by sooftware** [comment]
음 저건 다른 오류인 것 같은데 왜 저게 나는지는 생각해봐야겠네요.  
샘플레이트 8KHz로 학습시키시는 것보다 8KHz를 16KHz로 업샘플링해서 학습시키는걸 추천드려요.  
  
아무래도 포맷이 16KHz에 맞춰져 있다보니 그게 더 편하실 거에요. 실제로 ClovaCall 역시 업샘플링해서 만든 데이터셋이구요.  
퀄리티가 괜찮을거에요.

**Comment by mnbv7581** [comment]
![주파수차이2](https://user-images.githubusercontent.com/44501825/101309554-0f6a4180-3890-11eb-893d-70d48851cb3a.png)

그렇다면 8Khz의 음성을 16Khz음성으로 변경하여 학습할 때에 발생되는 문제는 없다고 말씀하시는 건가요?
실제 8Khz의 음성을 16Khz로 바꾸더라도 높은 주파수의 영역들은 생성되어지지 않고 비어있는 데이터처럼 된다고 생각되는데 이부분들이 학습에 영향을 미치진 않을까요?

**Comment by sooftware** [comment]
샘플레이트 같은 경우 1초에 몇 샘플이나 있느냐 하는 특성입니다. 실제로 16KHz로 녹음된 파일에 비해서 음질이 조금 떨어지겠지만, 업샘플링을 얼마나 잘하냐에 따라 달리지겠지요.  
  
주파수가 빈다는 말은 무슨 말씀이신지 제가 이해를 못한 것 같습니다.  
시간축에서 1초에 8천개의 샘플씩 있던 것을 16000개로 늘려주는게 업샘플링인데, 제가 놓친 부분이 있을까요?

**Comment by mnbv7581** [comment]
예시로 보여준 이미지는 kspon dataset 음원파일의 파형을 스펙트로그램으로 변환한 것이고 첫번째 음원같은 경우 8khz로 다운샘플링 한 후에 16khz로 업샘플링한 결과물입니다. 실제로 8khz데이터를 업샘플링 한다고 해서 잘려나간 높은 주파수의 영역의 데이터들이 표현되지 않아 비어있다는 표현을 했습니다. 만약 8khz로만 구성된 데이터셋들을 16khz로 업샘플링 하게되면 저러한 형태의 데이터들로만 학습되게 될텐데 표현되지않는 높은 영역의 주파수영역범위까지 입력데이터로 사용하게 되면 학습과정에서 좋지않은 결과가 나오지 않을까해서 물어보게 되었습니다. 훈련과정에서의 성능은 어느정도 나왔지만 테스트데이터에서의 성능이 상당히 좋지않았습니다. 드롭아웃 크기를 늘려서 해결할 수 있을까요?

**Comment by sooftware** [comment]
혹시 왜 다운샘플링 하셨는지 알수 있을까요? 다운샘플링 후 업샘플링시 당연하게도 정보손실이 있습니다. 테스트 데이터셋에서 어느 정도 차인지 모르겠지만 크게 차이난다면 피쳐쪽이 동일하게 뽑히는지를 봐야할 것 같습니다.

**Comment by mnbv7581** [comment]
앞으로 수집할 데이터가 8khz 샘플레이트에 128kbps 데이터 입니다. 이 이상의 음질을 수집할 환경이 되지않기에 8khz 음질로 테스트를 진행해보려 했습니다. 테스트데이터 이와 동일한 스펙에 데이터이고요. 피쳐쪽이 동일하게 뽑혔는지 봐한다는건 어떤걸 말씀하시는지 설명 부탁드려도 될까요?

**Comment by sooftware** [comment]
저라면 업샘플링을 해서 학습을 진행할 것 같습니다.  
업샘플링한 오디오를 들어보셨을 때, 음질이 크게 나쁘지 않다면 학습에 사용하실 수 있을거에요.  
   
아마 성능평가시 eval.sh쪽으로 실행하실 것 같은데, 학습 당시와 똑같은 피쳐 설정을 해주셔야 제대로 평가가 되실거에요.  
프레임 길이, 쉬프트 길이, Mel-Spectrogram, MFCC인지 등의 여부, input_reverse 옵션이 켜졌는지 꺼졌는지 여부 등에 따라 하나라도 다르면 모델이 제대로 인식을 못할거에요.  
  
테스트하기 좋은 방법은 학습에 사용한 데이터를 입력으로 넣어서 잘 인식하는지를 보면 될 것 같네요.

**Comment by mnbv7581** [comment]
아하.. 알겠습니다 내용참고해서 진행해보겠습니다. 감사합니다.
