### ISSUE TITLE
Pre-trained Model이 열리지 않습니다.

### ISSUE THREAD

**Issue by jaeseongyou** [sooftware/KoSpeech#63]
좋은 프로젝트 공유해주셔서 감사합니다.

올려두신 프리트레인드 모델의 .pt 파일을 torch.load로 로드하려고 하면 kospeech.models.las.las라는 모듈이 없다는 에러가 발생합니다.

**Comment by sooftware** [comment]
전에 학습했던 모델인데, 최근 코드 구조적 수정이 있어서 그런 것 같네요 ㅠ.ㅠ  
다시 학습하는대로 재업로드 해놓겠습니다.

**Comment by sooftware** [comment]
pre-train 모델을 업데이트 했습니다.
