### ISSUE TITLE
data_loader 셔플시 에러발생합니다..

### ISSUE THREAD

**Issue by KIMSeHyung** [sooftware/KoSpeech#68]
DeepSpeech2 모델 러닝시에.. 이런 오류가 나는데요
![image](https://user-images.githubusercontent.com/16644018/102990052-0a78e380-455a-11eb-9698-cb03354e92bd.png)

어떤문제인지 모르겠어서 이슈남겨봅니다..

**Comment by sooftware** [comment]
확인 되는대로 코멘트 남기겠습니다.

**Comment by KIMSeHyung** [comment]
@sooftware 감사합니다!

**Comment by sooftware** [comment]
현재 에러는 따로 나지 않는 것 같습니다.
