### ISSUE TITLE
Transformer를 이용한 추론

### ISSUE THREAD

**Issue by kimjeongtae** [sooftware/kospeech#93]
안녕하세요. 

우선  KoSpeech를 오픈소스로 공개해주셔서 감사합니다.

공개해주신 Tranformer모델(transformer_90-16.pt)을 이용해서 추론해보고 싶은데

python3 ./bin/inference.py --model_path transformer_90-16.pt --audio_path KsponSpeech_000001.pcm --device cuda

이렇게 실행하면 결과가 공백으로만 나옵니다.

audio_path에 KsponSpeech의 pcm파일 경로를 그냥 넣으면 안되는건가요?...

그리고 참고로 입력텐서를 device로 변환해주는 코드가 빠진거 같습니다.

감사합니다.

**Comment by sooftware** [comment]
트랜스포머 모델이 inference에 에러가 있네요. 확인되는대로 업데이트 해놓겠습니다.
