### ISSUE TITLE
Pre-trained 모델 공유 여부 문의

### ISSUE THREAD

**Issue by SoonbeomChoi** [sooftware/kospeech#98]
안녕하세요 좋은 코드를 오픈해주셔서 감사드립니다.
이 repository에 있는 모델들을 테스트 해보려하는데, pre-trained 모델은 없는 것 같아
혹시 공유가 별도로 되는지 문의 드립니다.

**Comment by sooftware** [comment]
네 안녕하세요. 기존에는 pre-train 모델을 제공했으나, 최근 (지금까지) 모델 코드를 refactoring 하는 중입니다.  
코드 refactoring을 크게 하고있는 중이라, 이 작업이 끝나면 다시 트레인해서 제공할 예정입니다.

**Comment by SoonbeomChoi** [comment]
그렇군요 답변 감사드립니다 :)
